const languages = {
  bod: 'Tibetan',
  tib: 'Tibetan',
  ces: 'Czech',
  cze: 'Czech',
  cym: 'Welsh',
  wel: 'Welsh',
  deu: 'German',
  ger: 'German',
  ell: 'Greek',
  gre: 'Greek',
  eus: 'Basque',
  baq: 'Basque',
  fas: 'Farsi (Persian)',
  per: 'Farsi (Persian)',
  fra: 'French',
  fre: 'French',
  hye: 'Armenian',
  arm: 'Armenian',
  isl: 'Icelandic',
  ice: 'Icelandic',
  kat: 'Georgian',
  geo: 'Georgian',
  mkd: 'Macedonian',
  mac: 'Macedonian',
  mri: 'Māori',
  mao: 'Māori',
  msa: 'Malay',
  may: 'Malay',
  mya: 'Burmese',
  bur: 'Burmese',
  nld: 'Flemish (Dutch)',
  dut: 'Flemish (Dutch)',
  ron: 'Romanian (Moldovan)',
  rum: 'Romanian (Moldovan)',
  slk: 'Slovak',
  slo: 'Slovak',
  sqi: 'Albanian',
  alb: 'Albanian',
  zho: 'Chinese',
  chi: 'Chinese',
  aar: 'Afar',
  abk: 'Abkhazian',
  afr: 'Afrikaans',
  aka: 'Akan',
  amh: 'Amharic',
  ara: 'Arabic',
  arg: 'Aragonese',
  asm: 'Assamese',
  ava: 'Avaric',
  ave: 'Avestan',
  aym: 'Aymara',
  aze: 'Azerbaijani',
  bak: 'Bashkir',
  bam: 'Bambara',
  bel: 'Belarusian',
  ben: 'Bangla (Bengali)',
  bis: 'Bislama',
  bos: 'Bosnian',
  bre: 'Breton',
  bul: 'Bulgarian',
  cat: 'Catalan; Valencian',
  cha: 'Chamorro',
  che: 'Chechen',
  chu: 'Church Slavic',
  chv: 'Chuvash',
  cor: 'Cornish',
  cos: 'Corsican',
  cre: 'Cree',
  dan: 'Danish',
  div: 'Divehi; Dhivehi; Maldivian',
  dzo: 'Dzongkha',
  eng: 'English',
  epo: 'Esperanto',
  est: 'Estonian',
  ewe: 'Ewe',
  fao: 'Faroese',
  fij: 'Fijian',
  fin: 'Finnish',
  fry: 'Western Frisian',
  ful: 'Fulah',
  gla: 'Gaelic; Scottish Gaelic',
  gle: 'Irish',
  glg: 'Galician',
  glv: 'Manx',
  grn: 'Guarani',
  guj: 'Gujarati',
  hat: 'Haitian; Haitian Creole',
  hau: 'Hausa',
  heb: 'Hebrew',
  her: 'Herero',
  hin: 'Hindi',
  hmo: 'Hiri Motu',
  hrv: 'Croatian',
  hun: 'Hungarian',
  ibo: 'Igbo',
  ido: 'Ido',
  iii: 'Sichuan Yi; Nuosu',
  iku: 'Inuktitut',
  ile: 'Interlingue; Occidental',
  ina: 'Interlingua (IALA)',
  ind: 'Indonesian',
  ipk: 'Inupiaq',
  ita: 'Italian',
  jav: 'Javanese',
  jpn: 'Japanese',
  kal: 'Kalaallisut; Greenlandic',
  kan: 'Kannada',
  kas: 'Kashmiri',
  kau: 'Kanuri',
  kaz: 'Kazakh',
  khm: 'Central Khmer',
  kik: 'Kikuyu; Gikuyu',
  kin: 'Kinyarwanda',
  kir: 'Kirghiz; Kyrgyz',
  kom: 'Komi',
  kon: 'Kongo',
  kor: 'Korean',
  kua: 'Kuanyama; Kwanyama',
  kur: 'Kurdish',
  lao: 'Lao',
  lat: 'Latin',
  lav: 'Latvian',
  lim: 'Limburgan; Limburger; Limburgish',
  lin: 'Lingala',
  lit: 'Lithuanian',
  ltz: 'Luxembourgish; Letzeburgesch',
  lub: 'Luba-Katanga',
  lug: 'Ganda',
  mah: 'Marshallese',
  mal: 'Malayalam',
  mar: 'Marathi',
  mlg: 'Malagasy',
  mlt: 'Maltese',
  mon: 'Mongolian',
  nau: 'Nauru',
  nav: 'Navajo',
  nbl: 'Ndebele, South',
  nde: 'Ndebele, North',
  ndo: 'Ndonga',
  nep: 'Nepali',
  nno: 'Norwegian Nynorsk; Nynorsk, Norwegian',
  nob: 'Bokmål, Norwegian; Norwegian Bokmål',
  nor: 'Norwegian',
  nya: 'Chichewa; Chewa; Nyanja',
  oci: 'Occitan',
  oji: 'Ojibwa',
  ori: 'Oriya',
  orm: 'Oromo',
  oss: 'Ossetian; Ossetic',
  pan: 'Panjabi; Punjabi',
  pli: 'Pali',
  pol: 'Polish',
  por: 'Portuguese',
  pus: 'Pushto; Pashto',
  que: 'Quechua',
  roh: 'Romansh',
  run: 'Rundi',
  rus: 'Russian',
  sag: 'Sango',
  san: 'Sanskrit',
  sin: 'Sinhala; Sinhalese',
  slv: 'Slovenian',
  sme: 'Northern Sami',
  smo: 'Samoan',
  sna: 'Shona',
  snd: 'Sindhi',
  som: 'Somali',
  sot: 'Sotho, Southern',
  spa: 'Spanish; Castilian',
  srd: 'Sardinian',
  srp: 'Serbian',
  ssw: 'Swati',
  sun: 'Sundanese',
  swa: 'Swahili',
  swe: 'Swedish',
  tah: 'Tahitian',
  tam: 'Tamil',
  tat: 'Tatar',
  tel: 'Telugu',
  tgk: 'Tajik',
  tgl: 'Tagalog',
  tha: 'Thai',
  tir: 'Tigrinya',
  ton: 'Tonga',
  tsn: 'Tswana',
  tso: 'Tsonga',
  tuk: 'Turkmen',
  tur: 'Turkish',
  twi: 'Twi',
  uig: 'Uyghur',
  ukr: 'Ukrainian',
  urd: 'Urdu',
  uzb: 'Uzbek',
  ven: 'Venda',
  vie: 'Vietnamese',
  vol: 'Volapük',
  wln: 'Walloon',
  wol: 'Wolof',
  xho: 'Xhosa',
  yid: 'Yiddish',
  yor: 'Yoruba',
  zha: 'Zhuang',
  zul: 'Zulu',
}

export default languages
